services:
  backend:
    build: ./backend
    ports:
      - "1337:1337"
    environment:
      URL: http://45.159.149.160:1337
      CORS_ORIGIN: http://45.159.149.160
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapiuser
      DATABASE_PASSWORD: Hajehs@n014709121474234
      APP_KEYS: Hiog2CQXtyCpKgEg360Qb03RwFXZafWycIdD1ueItwQ=,tyhm9m/lCxZ8vE7/FokwdOOl6wPZdRA9zLToNPNe8Y0=
      API_TOKEN_SALT: 2zer5ow1Xjstie7QEYYcgq9aGT70krRdqOela57n2cc=
      ADMIN_JWT_SECRET: q/HhQ40PdOD+coo0XrlTq+qjvz58r4kIGQwJeGZadbM=
      JWT_SECRET: XrCBgApPrv1maXqo80zVYjA9Og2kw8rCzQDRgiJS3b0=
    volumes:
      - strapi-uploads:/opt/app/public/uploads
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://45.159.149.160
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: strapiuser
      POSTGRES_PASSWORD: Hajehs@n014709121474234
      POSTGRES_DB: strapi_db
    volumes:
      - strapi-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  strapi-data:
  strapi-uploads:
